require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-sorbet

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"

Metrics/PerceivedComplexity:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"

Metrics/CyclomaticComplexity:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"

Metrics/BlockLength:
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/**/*"
    - "lib/tasks/**/*"
    - "spec/**/*"
