version: "3"

services:
  db:
    image: postgres:15.2
    container_name: postgres_rails_api_playground_db
    ports:
      - 15432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  db-store:
