import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "~/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{props.users[0].name}</p>
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const response = await fetch("http://127.0.0.1:3001/users", {
    method: "GET",
  });
  const json = await response.json();
  console.log(json);

  return {
    props: {
      users: json.data,
    },
  };
};
