---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/users":
    get:
      summary: Retrieves user list
      tags:
      - Users
      responses:
        '200':
          description: user list found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        created_at:
                          type: string
                        updated_at:
                          type: string
                      required:
                      - id
                      - name
                      - created_at
                      - updated_at
                required:
                - data
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
